### ISSUE TITLE
CAD files to adapt to cnc carriage

### ISSUE THREAD

**Issue by MaciejK98** [DW-Tas/Klicky-00#1]
Hello, I've got a cnc carriage for 2.4 and it has different dimensions than the printed one. Would it be possible to share a cad files of the klicky00 body as I would like to see how I need to modify the pcb stealthburner klicky mount.
![IMG_20240112_204319](https://github.com/DW-Tas/Klicky-00/assets/80107067/40b4619e-14b3-4f18-931d-e495f09ed2e4)

**Comment by DW-Tas** [comment]
release candidate CAD has been uploaded.
