### ISSUE TITLE
Stealth Burner edition with all M3 hardware?

### ISSUE THREAD

**Issue by PhilBaz** [DW-Tas/Klicky-00#2]
Hello,

Just wanted to ask if it's possible to transition the stealthburner edition (at least the D2f)  to all M3 hardware? Then it really will only include stuff we all have lying around. Probably 95% of voron owners don't have any M2.5 hardware. If everything was m3 that would make it instantly available to every Voron user and help with wider adoption. 

Just looking at the project from my perspective--a steallthburner + klicky + Auto-Z user, I'm most likely to choose the stealthburner D2f route as the path of least resistance. I imagine that will be the case with the majority of Voron owners. But maybe not. Just a thought. 

Interesting project, looking forward to trying it out. Thank you!

**Comment by DW-Tas** [comment]
RC2 has just been uploaded and is M3 instead of 2.5.

**Comment by PhilBaz** [comment]
@DW-Tas Ahh, amazing! I had no idea that was in the works...klicky-00 here I come!

Thank you!
