### ISSUE TITLE
BumpDock CAD

### ISSUE THREAD

**Issue by gvasvari** [DW-Tas/Klicky-00#3]
Hi, could you upload the BumpDock CAD as well?
I'd like to make an adaptation for the VzCNC-HevORT toolhead with Goliath hotend (currently building a Monolith AWD v2.4)
So far I made a toolhead mount on the Goliath duct for the Klicky-00 probe which seems to be working mechanically.

The problem with the BumpDock is that the upper arm - which has the PTFE insert on the outer face, towards the toolhead - collides with the rear fan duct elbow joint. I think I can make it work by shifting the 45deg chamfer of the arm further back. It is currently above the PTFE tube, but I see some room for change.

**Comment by DW-Tas** [comment]
Sure, here it is <https://github.com/DW-Tas/Klicky-00/blob/main/CAD/Klicky-00_Bump-Dock_assembly.step>
