### ISSUE TITLE
Missing PCB SB mount

### ISSUE THREAD

**Issue by HaernCalistinson** [DW-Tas/Klicky-00#4]
Without looking closely at what I was actually printing (I NEVER do that).. I didn't realize that the SB mount in the STL folder (STL/Klicky-00_AB-SB_mount_centered.stl) is for the non-pcb klicky. I could be completely blind, but I don't see the one for the PCB klicky mount. I can grab the one from the klicky pcb repo, but figured I'd drop a heads up.

**Comment by DW-Tas** [comment]
Hi. That's intentional. I haven't included one here, because I haven't modified the PCB klicky mount for SB.
